version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/usr/share/nginx/html
      - ./ssl:/etc/ssl/certs/nginx
    ports:
      - 80:80
    networks:
      - app
networks: 
  app:
    driver: bridge