version: "3.9"
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 83:80
    container_name: rapadura-wordpress
    restart: always
    environment:
      - TZ=America/Fortaleza
      - VIRTUAL_HOST=wordpress.rapadura.local
      - VIRTUAL_PORT=83
    logging: 
      driver: "json-file"
      options: 
        max-size: "5m"
        max-file: "2"
    networks:
      - app
networks: 
  app:
    driver: bridge